### ISSUE TITLE
Error ketika melakukan komunikasi OkHttp

### ISSUE THREAD

**Issue by ilhamfadllah** [pptik/sahabat-bawaslu-android#1]
> java.lang.NullPointerException: Attempt to invoke interface method 'retrofit2.Call id.pptik.ilham.sahabatbawaslu.networks.RestServiceInterface.createUser(id.pptik.ilham.sahabatbawaslu.networks.pojos.LoginPOJO)' on a null object reference
                                                                                 at id.pptik.ilham.sahabatbawaslu.features.login.LoginActivity.login(LoginActivity.java:47)

Pesan error ketika melakukan komunikasi OkHttp retrofit. Ada yang bisa bantu?

**Comment by ilhamfadllah** [comment]
Udah ketemu guys solusi masalah ini, gw lupa buat inisial kelas interface untuk kelas httpok client(Retrofit) nya. Thanks!

**Comment by hynra** [comment]
👍
